{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-optimizer.serviceAccountName" . }}
  labels:
    {{- include "node-optimizer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node-optimizer.fullname" . }}
  labels:
    {{- include "node-optimizer.labels" . | nindent 4 }}
rules:
# Core resources
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - nodes/stats
  - pods
  - pods/eviction
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["delete", "create", "patch", "update"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create", "patch"]

# Apps resources
- apiGroups: ["apps"]
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch", "patch", "update"]

# Metrics
- apiGroups: ["metrics.k8s.io"]
  resources:
  - nodes
  - pods
  verbs: ["get", "list"]

# Custom resources
- apiGroups: ["optimizer.io"]
  resources:
  - optimizationconfigs
  - migrationplans
  - optimizationreports
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["optimizer.io"]
  resources:
  - optimizationconfigs/status
  - migrationplans/status
  - optimizationreports/status
  verbs: ["get", "update", "patch"]

# Scheduling
- apiGroups: ["scheduling.k8s.io"]
  resources:
  - priorityclasses
  verbs: ["get", "list", "watch"]

# Policy
- apiGroups: ["policy"]
  resources:
  - poddisruptionbudgets
  verbs: ["get", "list", "watch"]

# Autoscaling
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling.k8s.io"]
  resources:
  - verticalpodautoscalers
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-optimizer.fullname" . }}
  labels:
    {{- include "node-optimizer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-optimizer.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "node-optimizer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}